CREATE TABLE IF NOT EXISTS BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR VARCHAR(255),
    PUBLICATION_YEAR INT,
    ISBN VARCHAR(20),
    AVAILABLE BOOLEAN
);
CREATE TABLE IF NOT EXISTS PATRONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CONTACT_INFORMATION VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS BORROWING_RECORDS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID BIGINT NOT NULL,
    PATRON_ID BIGINT NOT NULL,
    BORROW_DATE DATE NOT NULL,
    RETURN_DATE DATE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID),
    FOREIGN KEY (PATRON_ID) REFERENCES PATRONS(ID)
);
